#!/usr/bin/env bash
#
# Renders an nginx route from acl.json: one location per principal, each
# injecting that principal's API key.
#
# The route and the ACL are two views of the same list, so generating one from
# the other is what stops them drifting. Adding a consumer becomes a single edit
# to acl.json followed by a re-render.
#
#   ./render-route.sh > places.conf     # then install and reload nginx
#   ACL=/path/to/acl.json UPSTREAM=http://127.0.0.1:8010/ ./render-route.sh
#
# The output contains real API keys. Keep it out of version control, mode 600.

set -euo pipefail

ACL=${ACL:-$(dirname "$0")/acl.json}
UPSTREAM=${UPSTREAM:-http://127.0.0.1:8010/}
PREFIX=${PREFIX:-/api/places}
AGENT_HEADER=${AGENT_HEADER:-}
MAX_BODY=${MAX_BODY:-12m}

[ -f "$ACL" ] || { echo "render-route: $ACL not found" >&2; exit 1; }

ACL="$ACL" UPSTREAM="$UPSTREAM" PREFIX="$PREFIX" AGENT_HEADER="$AGENT_HEADER" MAX_BODY="$MAX_BODY" \
python3 <<'PY'
import json, os, re, sys

acl = json.load(open(os.environ["ACL"], encoding="utf-8"))
upstream = os.environ["UPSTREAM"]
prefix = os.environ["PREFIX"].rstrip("/")
agent_header = os.environ.get("AGENT_HEADER", "")
max_body = os.environ["MAX_BODY"]

print(f"""# GENERATED by render-route.sh from acl.json — do not edit by hand.
#
# One location per principal. nginx stamps the key, so the consumer holds no
# credential at all and cannot promote itself by sending a different one: the
# proof of identity is the path the request arrived on.
#
# Caveat worth keeping in view: any process that can reach this listener can
# call every location on it. Two principals are only meaningfully separated
# here if the narrower one cannot open sockets — so give the broader scope to
# the consumer that has shell access, never the other way round.
#
# client_max_body_size is set uniformly rather than only on the routes that
# accept photos. Working out which principals hold photo.upload would mean
# restating the role table from acl.ts in a shell script, and a second copy of
# an access rule is worse than a loose outer limit: the service enforces
# PHOTO_MAX_BYTES itself, and this is only here because nginx defaults to 1 MB,
# which is smaller than any photograph a phone produces.
#
# Regenerate after editing acl.json:
#   ./render-route.sh > places.conf && install -m 600 -o root -g root places.conf <dest>
#   nginx -t && systemctl reload nginx""")

for name, principal in acl.get("principals", {}).items():
    if not re.fullmatch(r"[a-z0-9][a-z0-9_-]*", name):
        sys.exit(f"render-route: principal name {name!r} is not safe for a URL path")

    scope = principal.get("role", "?")
    extra = []
    if principal.get("allow"):
        extra.append("plus " + ", ".join(principal["allow"]))
    if principal.get("deny"):
        extra.append("minus " + ", ".join(principal["deny"]))
    described = f"{scope}{' (' + '; '.join(extra) + ')' if extra else ''}"

    print(f"""
# {name} — {described}
location {prefix}/{name}/ {{
    proxy_pass {upstream};
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;

    # Replaces any X-Api-Key the caller sent.
    proxy_set_header X-Api-Key {principal['apiKey']};""")
    if agent_header:
        print(f"    proxy_set_header X-Openclaw-Agent {agent_header};")
    print(f"""
    # Required for the MCP SSE keep-alive on GET /mcp.
    proxy_set_header Connection '';
    proxy_buffering off;

    client_max_body_size {max_body};
    proxy_read_timeout 120s;
    proxy_connect_timeout 10s;
}}""")
PY
