// render.test.ts
//
// The snapshot is the point. `POST /render?all=true` rewrites every published
// file at once, and the only thing standing between a template tweak and two
// thousand mangled pages is a test that says exactly what the output looks like.

import { describe, expect, test } from "bun:test";

import { parsePlace, serialisePlace, type Place } from "./model";
import { GENERATED_NOTICE, humanise, renderPlace } from "./render";

function fullPlace(): Place {
  return parsePlace({
    slug: "fonte-da-pipa",
    title: "Fonte da Pipa",
    kind: ["flores"],
    tags: ["Serra da Estrela"],
    summary: "Curva da estrada acima da fonte; campo aberto virado a sul.",
    address: "N339, junto ao marco 12",
    coords: { lat: 40.326110, lon: -7.613890 },
    body: "Estaciona-se na berma larga a seguir à curva.",
    created: "2026-04-12T10:12:00+01:00",
    updated: "2026-08-31T09:40:00+01:00",
    entries: [
      {
        id: "e9b104",
        date: "2026-08-31",
        type: "sighting",
        by: "thilia",
        species: ["cardo"],
        note: "já seco, mas há muito",
        photos: [{ id: "p71aa3", file: "2026-08-31-cardo.jpg" }],
      },
      {
        id: "e7f3a2",
        date: "2026-04-12",
        type: "sighting",
        by: "thiago",
        species: ["papoila-das-searas", "malmequer-bravo"],
        note: "campo todo vermelho no lado sul",
        photos: [
          { id: "p2c81f", file: "2026-04-12-papoila-1.jpg" },
          { id: "p3d92a", file: "2026-04-12-papoila-2.jpg", caption: "de perto" },
        ],
      },
    ],
  });
}

const EXPECTED = `---
# GENERATED by scholion-places from place.json — do not edit.
# Any change made here is lost on the next render. Edit place.json instead,
# or use the API; the prose of the place lives in its "body" field.

title: "Fonte da Pipa"
date: "2026-04-12T10:12:00+01:00"
lastmod: "2026-08-31T09:40:00+01:00"
category: place
summary: "Curva da estrada acima da fonte; campo aberto virado a sul."
tags: ["serra-da-estrela"]
kind: ["flores"]
species: ["cardo", "malmequer-bravo", "papoila-das-searas"]
coords: [40.32611, -7.61389]
address: "N339, junto ao marco 12"
thumb: "2026-04-12-papoila-1.jpg"
---

Estaciona-se na berma larga a seguir à curva.

## 2026-04-12 — Malmequer bravo, Papoila das searas

campo todo vermelho no lado sul

![Malmequer bravo, Papoila das searas](2026-04-12-papoila-1.jpg)

![de perto](2026-04-12-papoila-2.jpg)

## 2026-08-31 — Cardo

já seco, mas há muito

![Cardo](2026-08-31-cardo.jpg)
`;

describe("renderPlace", () => {
  test("produces exactly the published Markdown", () => {
    expect(renderPlace(fullPlace())).toBe(EXPECTED);
  });

  test("is pure: same record in, same bytes out", () => {
    const place = fullPlace();
    expect(renderPlace(place)).toBe(renderPlace(place));
  });

  test("rendering does not touch the record", () => {
    const place = fullPlace();
    const before = serialisePlace(place);
    renderPlace(place);
    expect(serialisePlace(place)).toBe(before);
  });

  test("says loudly that it is generated", () => {
    const output = renderPlace(fullPlace());
    for (const line of GENERATED_NOTICE) expect(output).toContain(line);
    // Inside the frontmatter, so Hugo parses it as a YAML comment and drops it.
    expect(output.indexOf(GENERATED_NOTICE[0])).toBeLessThan(output.indexOf("title:"));
  });

  test("the sections are chronological, whatever order the entries arrived in", () => {
    const output = renderPlace(fullPlace());
    expect(output.indexOf("## 2026-04-12")).toBeLessThan(output.indexOf("## 2026-08-31"));
  });
});

describe("a sparse place still renders", () => {
  test("no body, no entries, no optional fields", () => {
    const place = parsePlace({
      title: "Sítio Novo",
      coords: { lat: 40, lon: -7 },
      created: "2026-09-01T08:00:00+01:00",
      updated: "2026-09-01T08:00:00+01:00",
    });
    expect(renderPlace(place)).toBe(`---
${GENERATED_NOTICE.join("\n")}

title: "Sítio Novo"
date: "2026-09-01T08:00:00+01:00"
lastmod: "2026-09-01T08:00:00+01:00"
category: place
coords: [40, -7]
---
`);
  });

  test("an entry with neither species nor dish is still headed by its date", () => {
    const place = parsePlace({
      title: "x",
      coords: { lat: 40, lon: -7 },
      entries: [{ id: "e00001", date: "2026-05-03", type: "visit", by: "thiago", rating: 4 }],
    });
    const output = renderPlace(place);
    expect(output).toContain("## 2026-05-03 — Visita");
    expect(output).toContain("Nota: ★★★★☆");
  });

  test("quotes and backslashes in a title do not break the frontmatter", () => {
    const place = parsePlace({
      title: 'O "Alto" da Serra \\ norte',
      coords: { lat: 40, lon: -7 },
    });
    expect(renderPlace(place)).toContain('title: "O \\"Alto\\" da Serra \\\\ norte"');
  });
});

describe("thumb", () => {
  test("is the first photo of the earliest visit, whatever the filenames sort like", () => {
    // "…-hortensia-2.jpg" sorts before "…-hortensia.jpg", so a site picking by
    // filename would show the second photograph. The record settles it.
    const place = parsePlace({
      title: "x",
      coords: { lat: 40, lon: -7 },
      entries: [
        {
          id: "e00002",
          date: "2026-08-31",
          by: "thiago",
          photos: [
            { id: "p00001", file: "2026-08-31-hortensia.jpg" },
            { id: "p00002", file: "2026-08-31-hortensia-2.jpg" },
          ],
        },
        { id: "e00001", date: "2026-04-12", by: "thiago", photos: [{ id: "p00003", file: "2026-04-12-cardo.jpg" }] },
      ],
    });
    expect(renderPlace(place)).toContain('thumb: "2026-04-12-cardo.jpg"');
  });

  test("a place with no photographs declares none", () => {
    const place = parsePlace({ title: "x", coords: { lat: 40, lon: -7 } });
    expect(renderPlace(place)).not.toContain("thumb:");
  });
});

describe("humanise", () => {
  test("turns a normalised label back into prose", () => {
    expect(humanise("papoila-das-searas")).toBe("Papoila das searas");
    expect(humanise("cardo")).toBe("Cardo");
  });
});
