// render.ts — the exposure layer, and the only module that knows what Markdown is.
//
// place.json is the record; index.md is a view of it. Keeping the two apart is
// what lets a layout change be a re-render and a commit instead of a migration:
// nothing reads the Markdown back, so it can be rewritten from scratch at any
// time without risk to the data.
//
// Two consequences follow, and both are deliberate:
//
//   - Hand edits to index.md are lost on the next render. The file says so, in
//     a YAML comment that Hugo ignores and a person cannot miss.
//   - Because the body is generated, it can be generous. Writing the visits as
//     dated sections reads far better than a YAML list, and costs nothing:
//     the search index is built from the JSON, never from this prose.
//
// Rendering is pure. Same record in, same bytes out — which is what makes the
// snapshot test worth having and the mass re-render safe to review as a diff.

import { speciesOf, sortEntries, type Entry, type Place } from "./model";

export const GENERATED_NOTICE = [
  "# GENERATED by scholion-places from place.json — do not edit.",
  "# Any change made here is lost on the next render. Edit place.json instead,",
  "# or use the API; the prose of the place lives in its \"body\" field.",
];

/** Turn a normalised label back into something a person reads. */
export function humanise(label: string): string {
  const spaced = label.replace(/-/g, " ");
  return spaced.charAt(0).toUpperCase() + spaced.slice(1);
}

// ── a small, deliberate YAML emitter ─────────────────────────────────────────
//
// Bun ships Bun.YAML.stringify, and this does less than it does. That is the
// point: frontmatter is a small closed set of fields, and controlling the exact
// output — flow-style lists, stable key order, no surprise line wrapping — is
// what keeps `render --all` producing a reviewable diff instead of noise.

function yamlString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, " ")}"`;
}

function yamlList(values: string[]): string {
  return `[${values.map(yamlString).join(", ")}]`;
}

function yamlNumberList(values: number[]): string {
  return `[${values.join(", ")}]`;
}

function frontmatter(place: Place): string[] {
  const lines: string[] = [...GENERATED_NOTICE, ""];
  const species = speciesOf(place);

  lines.push(`title: ${yamlString(place.title)}`);
  lines.push(`date: ${yamlString(place.created)}`);
  lines.push(`lastmod: ${yamlString(place.updated)}`);
  lines.push("category: place");
  if (place.summary) lines.push(`summary: ${yamlString(place.summary)}`);
  if (place.tags.length) lines.push(`tags: ${yamlList(place.tags)}`);
  if (place.kind.length) lines.push(`kind: ${yamlList(place.kind)}`);
  if (species.length) lines.push(`species: ${yamlList(species)}`);
  lines.push(`coords: ${yamlNumberList([place.coords.lat, place.coords.lon])}`);
  if (place.address) lines.push(`address: ${yamlString(place.address)}`);

  return lines;
}

// ── the body ─────────────────────────────────────────────────────────────────

/**
 * The heading of one visit: the date, then what was found.
 *
 * A sighting is named by its species, a meal by its dish. When neither is
 * recorded the date alone still carries the entry — an undated blank section
 * would be worse than a terse one.
 */
function entryHeading(entry: Entry): string {
  const what =
    entry.type === "sighting"
      ? (entry.species ?? []).map(humanise).join(", ")
      : entry.dish ?? "";
  const label = what || (entry.type === "sighting" ? "Avistamento" : "Visita");
  return `## ${entry.date} — ${label}`;
}

function entryLines(entry: Entry): string[] {
  const lines = [entryHeading(entry), ""];

  if (entry.type === "visit" && entry.rating) {
    lines.push(`Nota: ${"★".repeat(entry.rating)}${"☆".repeat(5 - entry.rating)}`, "");
  }
  if (entry.note) lines.push(entry.note, "");

  const fallbackAlt = (entry.species ?? []).map(humanise).join(", ");
  for (const photo of entry.photos) {
    lines.push(`![${photo.caption ?? fallbackAlt}](${photo.file})`, "");
  }

  return lines;
}

/**
 * Render a place to the Markdown that Hugo publishes.
 *
 * Photos are referenced by bare filename, which resolves inside a page bundle —
 * the reason a place is a directory and not a single file.
 */
export function renderPlace(place: Place): string {
  const lines: string[] = ["---", ...frontmatter(place), "---", ""];

  if (place.body) lines.push(place.body.trim(), "");

  const entries = sortEntries(place.entries);
  for (const entry of entries) lines.push(...entryLines(entry));

  // Collapse runs of blank lines, then end with exactly one newline. Without
  // this the diff of a re-render is full of whitespace-only changes.
  const body = lines.join("\n").replace(/\n{3,}/g, "\n\n").replace(/\s+$/, "");
  return `${body}\n`;
}
